/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

DELETE dbo.Country
DBCC CHECKIDENT ('dbo.Country', RESEED, 1);  
INSERT INTO dbo.Country (CtyRef,CtyLabel) VALUES('AD', 'AD-Andorra')
,('AE', 'AE-United arab emirates')
,('AF', 'AF-Afghanistan')
,('AG', 'AG-Antigua and barbuda')
,('AI', 'AI-Anguilla')
,('AL', 'AL-Albania')
,('AM', 'AM-Armenia')
,('AN', 'AN-Netherlands Antilles')
,('AO', 'AO-Angola')
,('AQ', 'AQ-Antarctica')
,('AR', 'AR-Argentina')
,('AS', 'AS-American samoa')
,('AT', 'AT-Austria')
,('AU', 'AU-Australia')
,('AW', 'AW-Aruba')
,('AX', 'AX-Aland islands')
,('AZ', 'AZ-Azerbaijan')
,('BA', 'BA-Bosnia and Herzegovina')
,('BB', 'BB-Barbados')
,('BD', 'BD-Bangladesh')
,('BE', 'BE-Belgium')
,('BF', 'BF-Burkina Faso')
,('BG', 'BG-Bulgaria')
,('BH', 'BH-Bahrain')
,('BI', 'BI-Burundi')
,('BJ', 'BJ-Benin')
,('BL', 'BL-Saint barthélemy')
,('BM', 'BM-Bermuda')
,('BN', 'BN-Brunei Darussalam')
,('BO', 'BO-Bolivia')
,('BQ', 'BQ-Bonaire, sint eustatius and saba')
,('BR', 'BR-Brazil')
,('BS', 'BS-Bahamas')
,('BT', 'BT-Bhutan')
,('BV', 'BV-Bouvet island')
,('BW', 'BW-Botswana')
,('BY', 'BY-Belarus')
,('BZ', 'BZ-Belize')
,('CA', 'CA-Canada')
,('CC', 'CC-Cocos (keeling) islands')
,('CD', 'CD-Congo, the democratic republic of the')
,('CF', 'CF-Central African Republic')
,('CG', 'CG-Congo')
,('CH', 'CH-Switzerland')
,('CI', 'CI-Côte d''Ivoire')
,('CK', 'CK-Cook islands')
,('CL', 'CL-Chile')
,('CM', 'CM-Cameroon')
,('CN', 'CN-China')
,('CO', 'CO-Colombia')
,('CR', 'CR-Costa Rica')
,('CU', 'CU-Cuba')
,('CV', 'CV-Cape Verde')
,('CW', 'CW-Curaçao')
,('CX', 'CX-Christmas island')
,('CY', 'CY-Cyprus')
,('CZ', 'CZ-Czech Republic')
,('DE', 'DE-Germany')
,('DJ', 'DJ-Djibouti')
,('DK', 'DK-Denmark')
,('DM', 'DM-Dominica')
,('DO', 'DO-Dominican Republic')
,('DZ', 'DZ-Algeria')
,('EC', 'EC-Ecuador')
,('EE', 'EE-Estonia')
,('EG', 'EG-Egypt')
,('EH', 'EH-Western sahara')
,('ER', 'ER-Eritrea')
,('ES', 'ES-Spain')
,('ET', 'ET-Ethiopia')
,('FI', 'FI-Finland')
,('FJ', 'FJ-Fiji')
,('FK', 'FK-Falkland islands (malvinas)')
,('FM', 'FM-Micronesia, federated states of')
,('FO', 'FO-Faroe Islands')
,('FR', 'FR-France')
,('GA', 'GA-Gabon')
,('GB', 'GB-United Kingdom')
,('GD', 'GD-Grenada')
,('GE', 'GE-Georgia')
,('GG', 'GG-Guernsey')
,('GH', 'GH-Ghana')
,('GI', 'GI-Gibraltar')
,('GL', 'GL-Greenland')
,('GM', 'GM-Gambia')
,('GN', 'GN-Guinea')
,('GQ', 'GQ-Equatorial Guinea')
,('GR', 'GR-Greece')
,('GS', 'GS-South georgia and the south sandwich islands')
,('GT', 'GT-Guatemala')
,('GU', 'GU-Guam')
,('GW', 'GW-Guinea-Bissau')
,('GY', 'GY-Guyana')
,('HK', 'HK-Hong Kong')
,('HM', 'HM-Heard island and mcdonald islands')
,('HN', 'HN-Honduras')
,('HR', 'HR-Croatia')
,('HT', 'HT-Haiti')
,('HU', 'HU-Hungary')
,('ID', 'ID-Indonesia')
,('IE', 'IE-Ireland')
,('IL', 'IL-Israel')
,('IM', 'IM-Isle of man')
,('IN', 'IN-India')
,('IQ', 'IQ-Iraq')
,('IR', 'IR-Iran')
,('IS', 'IS-Iceland')
,('IT', 'IT-Italy')
,('JE', 'JE-Jersey')
,('JM', 'JM-Jamaica')
,('JO', 'JO-Jordan')
,('JP', 'JP-Japan')
,('KE', 'KE-Kenya')
,('KG', 'KG-Kyrgyzstan')
,('KH', 'KH-Cambodia')
,('KI', 'KI-Kiribati')
,('KM', 'KM-Comoros')
,('KN', 'KN-Saint kitts and nevis')
,('KP', 'KP-Korea, democratic people''s republic of')
,('KR', 'KR-Korea, republic of')
,('KW', 'KW-Kuwait')
,('KY', 'KY-Cayman islands')
,('KZ', 'KZ-Kazakhstan')
,('LA', 'LA-Lao People''s Democratic Republic')
,('LB', 'LB-Lebanon')
,('LC', 'LC-Saint lucia')
,('LI', 'LI-Liechtenstein')
,('LK', 'LK-Sri Lanka')
,('LR', 'LR-Liberia')
,('LS', 'LS-Lesotho')
,('LT', 'LT-Lithuania')
,('LU', 'LU-Luxembourg')
,('LV', 'LV-Latvia')
,('LY', 'LY-Lybia')
,('MA', 'MA-Morocco')
,('MC', 'MC-Monaco')
,('MD', 'MD-Moldova')
,('ME', 'ME-Montenegro')
,('MG', 'MG-Madagascar')
,('MH', 'MH-Marshall islands')
,('MK', 'MK-Macedonia')
,('ML', 'ML-Mali')
,('MM', 'MM-Myanmar')
,('MN', 'MN-Mongolia')
,('MO', 'MO-Macao')
,('MP', 'MP-Northern mariana islands')
,('MR', 'MR-Mauritania')
,('MS', 'MS-Montserrat')
,('MT', 'MT-Malta')
,('MU', 'MU-Mauritius')
,('MV', 'MV-Maldives')
,('MW', 'MW-Malawi')
,('MX', 'MX-Mexico')
,('MY', 'MY-Malaysia')
,('MZ', 'MZ-Mozambique')
,('NA', 'NA-Namibia')
,('NC', 'NC-New Caledonia')
,('NE', 'NE-Niger')
,('NF', 'NF-Norfolk island')
,('NG', 'NG-Nigeria')
,('NI', 'NI-Nicaragua')
,('NL', 'NL-Netherlands')
,('NO', 'NO-Norway')
,('NP', 'NP-Nepal')
,('NR', 'NR-Nauru')
,('NU', 'NU-Niue')
,('NZ', 'NZ-New Zealand')
,('OM', 'OM-Oman')
,('PA', 'PA-Panama')
,('PE', 'PE-Peru')
,('PF', 'PF-French Polynesia')
,('PG', 'PG-Papua New Guinea')
,('PH', 'PH-Philippines')
,('PK', 'PK-Pakistan')
,('PL', 'PL-Poland')
,('PM', 'PM-Saint pierre and miquelon')
,('PN', 'PN-Pitcairn')
,('PR', 'PR-Puerto Rico')
,('PS', 'PS-Palestinian Territories')
,('PT', 'PT-Portugal')
,('PW', 'PW-Palau')
,('PY', 'PY-Paraguay')
,('QA', 'QA-Qatar')
,('RO', 'RO-Romania')
,('RS', 'RS-Serbia')
,('RU', 'RU-Russian Federation')
,('RW', 'RW-Rwanda')
,('SA', 'SA-Saudi Arabia')
,('SB', 'SB-Solomon Islands')
,('SC', 'SC-Seychelles')
,('SD', 'SD-Sudan')
,('SE', 'SE-Sweden')
,('SG', 'SG-Singapore')
,('SH', 'SH-Saint helena, ascension and tristan da cunha')
,('SI', 'SI-Slovenia')
,('SJ', 'SJ-Svalbard and jan mayen')
,('SK', 'SK-Slovakia')
,('SL', 'SL-Sierra Leone')
,('SM', 'SM-San Marino')
,('SN', 'SN-Senegal')
,('SO', 'SO-Somalia')
,('SR', 'SR-Suriname')
,('SS', 'SS-South sudan')
,('ST', 'ST-Sao tome and principe')
,('SV', 'SV-El Salvador')
,('SY', 'SY-Syria')
,('SZ', 'SZ-Swaziland')
,('TC', 'TC-Turks and caicos islands')
,('TD', 'TD-Chad')
,('TG', 'TG-Togo')
,('TH', 'TH-Thailand')
,('TJ', 'TJ-Tajikistan')
,('TK', 'TK-Tokelau')
,('TL', 'TL-Timor-leste')
,('TM', 'TM-Turkmenistan')
,('TN', 'TN-Tunisia')
,('TO', 'TO-Tonga')
,('TR', 'TR-Turkey')
,('TT', 'TT-Trinidad and tobago')
,('TV', 'TV-Tuvalu')
,('TW', 'TW-Taiwan')
,('TZ', 'TZ-Tanzania')
,('UA', 'UA-Ukraine')
,('UG', 'UG-Uganda')
,('UM', 'UM-United states minor outlying islands')
,('US', 'US-United States')
,('UY', 'UY-Uruguay')
,('UZ', 'UZ-Uzbekistan')
,('VA', 'VA-Holy See')
,('VC', 'VC-Saint vincent and the grenadines')
,('VE', 'VE-Venezuela')
,('VG', 'VG-Virgin islands, british')
,('VI', 'VI-Virgin islands, u.s.')
,('VN', 'VN-Viet Nam')
,('VU', 'VU-Vanuatu')
,('WF', 'WF-Wallis and futuna')
,('WS', 'WS-Samoa')
,('XK', 'XK-Kosovo')
,('YE', 'YE-Yemen')
,('ZA', 'ZA-South Africa')
,('ZM', 'ZM-Zambia')
,('ZW', 'ZW-Zimbabwe');